language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install pylint flake8
script:
  - flake8 --ignore=E501
  - pylint bot.py modules/* -E

env:
  global:
  - IMAGE_NAME=pyemtvlc-bot
  - REGISTRY_USER=andoniaf
  - VERSION=$(date '+%Y%m%d%H%M%S')

before_deploy:
  - docker build -t "$IMAGE_NAME" .
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker tag "$IMAGE_NAME" "${REGISTRY_USER}/${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${REGISTRY_USER}/${IMAGE_NAME}:${VERSION}"

deploy:
  provider: script
  script: 
  - docker push "${REGISTRY_USER}/${IMAGE_NAME}:latest"
  - docker push "${REGISTRY_USER}/${IMAGE_NAME}:${VERSION}"
  on:
    branch: master

