language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
  - pip install pylint flake8
script:
  - flake8 --ignore=E501
  - pylint bot.py modules/* -E

env:
  global:
  - IMAGE_NAME=pyemtvlc-bot
  - REGISTRY_USER=andoniaf
  - HEROKU_USER=andonialonsof@gmail.com
  - HEROKU_APP=pyemtvlc
  - VERSION=$(date '+%Y%m%d%H%M%S')

before_deploy:
  - docker build -t "$IMAGE_NAME" .
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  - echo "$HEROKU_PASS" | docker login -u "$HEROKU_USER" --password-stdin registry.heroku.com
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker tag "$IMAGE_NAME" "${REGISTRY_USER}/${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${REGISTRY_USER}/${IMAGE_NAME}:${VERSION}"
  - docker tag "${REGISTRY_USER}/${IMAGE_NAME}:latest" registry.heroku.com/$HEROKU_APP/worker

deploy:
  provider: script
  script: 
    docker push "${REGISTRY_USER}/${IMAGE_NAME}:latest" 
    docker push "${REGISTRY_USER}/${IMAGE_NAME}:${VERSION}"
    docker push registry.heroku.com/$HEROKU_APP/worker;
    heroku container:release worker --app $HEROKU_APP
  on:
    branch: master

